export const lv = {
  main: "Sākums",
  locations: "Adreses",
  address: "Adrese",
  info: "Informācija",
  gallery: "Galerija",
  contacts: "Kontakti",
  language: "Valoda",
  InfoZona: "Telpa",
  contactUs: "Sazinies ar mums",
  back: "Adgriesties",
  available: "Pieejamas",
  unavailable: "Nepieejamas",
  moreInfo: "Vairāk informācijas",
  floor: "Stāvs",
  office: "Birojs",
  warehouse: "Noliktava",
};
export const eng = {
  main: "Home",
  locations: "Address",
  address: "Address",
  info: "Info",
  gallery: "Gallery",
  contacts: "Contacts",
  language: "Language",
  InfoZona: "Area",
  contactUs: "Contact Us",
  back: "Back",
  available: "Available",
  unavailable: "Not available",
  moreInfo: "More info",
  floor: "Floor",
  office: "office",
  warehouse: "Warehouse",
};
export const RU = {
  main: "Главная",
  locations: "адреса",
  info: "Информация",
  address: "Adrese",
  gallery: "галерея",
  contacts: "контакты",
  language: "язык",
  InfoZona: "зона",
  contactUs: "позвони нам",
  back: "назад",
  available: "доступный",
  unavailable: "недоступен",
  moreInfo: "узнать больше",
  floor: "Stāvs",
  office: "офис",
  warehouse: "Склад",
};
