url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/austris" # the subpath of your site, e.g. /blog
title: "AD" # the name of your site, e.g. ACME Corp.

sass:
    sass_dir: assets/css
    style: compressed
