url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Landing" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: compressed

autoprefixer:
  browsers:
    - last 5 versions
